import type { Metadata } from "next";
import { Inter, Cormorant_Garamond, Proza_Libre } from "next/font/google";
import Layout from "./components/layout";
import "./globals.scss";

const cormorant_garamond = Cormorant_Garamond({
  weight: ["400", "600"],
  display: 'swap',
  variable: '--font-cormorant_garamond',
  subsets: ["latin"],
  style: ['normal', 'italic'],
})
const proza_libre = Proza_Libre({
  weight: "400",
  display: 'swap',
  variable: '--font-proza_libre',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className={`${cormorant_garamond.variable} ${proza_libre.variable}`}>
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>

  );
}
